"""Generate crates/geometry/src/font_metrics.rs from the renderer's default font.

Headless code (engine hit-testing, bounding boxes, culling) must measure text the
way the renderer draws it. The renderer lays text out with the advance widths of
`Inter-Regular-subset.ttf` (no kerning); this script writes those advances and the
vertical metrics as a sorted table, so `dotloom-geometry` needs no font parser.

Usage:  python -m pip install fonttools==4.66.1
        python crates/render/assets/text-metrics.py
A render-crate test checks the table against the font the renderer loads.
"""

import os

from fontTools.ttLib import TTFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "geometry", "src", "font_metrics.rs")

font = TTFont(os.path.join(HERE, "Inter-Regular-subset.ttf"))
upm = font["head"].unitsPerEm
hhea = font["hhea"]
cap = font["glyf"]["H"].yMax
hmtx = font["hmtx"]
rows = sorted((cp, hmtx[name][0]) for cp, name in font.getBestCmap().items())
notdef = hmtx[".notdef"][0]

lines = [
    "//! Metrics of the renderer's default font (Inter 4.1 Regular subset, SIL OFL 1.1).",
    "//!",
    "//! Generated by `crates/render/assets/text-metrics.py` — do not edit. Checked against",
    "//! the font file by `crates/render/src/text.rs` tests.",
    "",
    f"/// Font units per em.\npub(crate) const UNITS_PER_EM: f64 = {upm}.0;",
    f"/// Top of `H` (cap height) in font units.\npub(crate) const CAP_HEIGHT: f64 = {cap}.0;",
    f"/// `hhea` ascender in font units.\npub(crate) const ASCENT: f64 = {hhea.ascent}.0;",
    f"/// `hhea` descender (positive) in font units.\npub(crate) const DESCENT: f64 = {-hhea.descent}.0;",
    f"/// Advance of the missing-glyph shape in font units.\npub(crate) const NOTDEF_ADVANCE: u16 = {notdef};",
    "",
    "/// `(code point, advance in font units)`, sorted by code point.",
    f"pub(crate) static ADVANCES: [(u32, u16); {len(rows)}] = [",
]
for i in range(0, len(rows), 6):
    lines.append("    " + " ".join(f"({cp:#06x}, {adv})," for cp, adv in rows[i : i + 6]))
lines.append("];")
with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(f"wrote {len(rows)} advances to {os.path.normpath(OUT)}")
